### ISSUE TITLE
[ERROR] when editing Question

### ISSUE THREAD

**Issue by yanseo** [designwall/dw-question-answer#102]
We're at the final stage implementation but for some reasons, we're stuck with this issue.
The error occurs when user wants to edit Question 

<b>Note: updating Answer works perfectly.</b>

Here's the message

<code>Notice: Undefined variable: post_submit_filter in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/dw-question-answer/inc/actions.php on line 886</code>

<code>Warning: Cannot modify header information – headers already sent by (output started at /Applications/MAMP/htdocs/wordpress/wp-content/plugins/dw-question-answer/inc/actions.php:886) in/Applications/MAMP/htdocs/wordpress/wp-includes/pluggable.php on line 1121
0 </code>

I check <code>the variable</code> and it is defined. Am I missing something here?

Thanks!

**Comment by anna2810** [comment]
Hey guys,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
