### ISSUE TITLE
Question author can not view his own private question

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#108]
Produce: 
- Go to Ask a question page to start asking a question.
- Select " post this question as private"
Results:
- Go to Questions list page, can't see own private question. However, as admin, totally view the private question

![can-nt-see-private-question](https://cloud.githubusercontent.com/assets/6157366/4470435/f6e91592-4925-11e4-9d51-3a08a69085ea.png)

As admin, you can see private question easily

![admin-private-question](https://cloud.githubusercontent.com/assets/6157366/4470444/3c58bb1e-4926-11e4-890b-2bf4345ceb58.png)

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
