### ISSUE TITLE
Redirect to archive page when filtering questions by tags

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#110]
- Go to the single question page 
- here, click on the tag of the question to view all questions which belong to those.
- however, the result page contains other tags

![correct-tag](https://cloud.githubusercontent.com/assets/6157366/4539746/40b7f39e-4e00-11e4-9046-0b8577c37805.png)

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
