### ISSUE TITLE
Show both private/public box and status box at the same time

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#111]
![show-both-private-public](https://cloud.githubusercontent.com/assets/6157366/4471888/1e38e9aa-4940-11e4-8102-5526e216d406.png)

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
