### ISSUE TITLE
Paging of the plguin shows correctly in only admin page

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#112]
- In back-end settings, set up to show at most 5 questions

![show-at-most-5-question](https://cloud.githubusercontent.com/assets/6157366/4472240/e0d2ea48-4944-11e4-9125-eaf1121288f0.png)

- as admin to view all questions, the number of questions show correctly

![show-correctly-posts](https://cloud.githubusercontent.com/assets/6157366/4472333/f8436ca6-4945-11e4-8d17-2c1e910ad7ff.png)

- But as subscriber or anonymous, the number of questions per each page are not correct.

![show-wrong-questions](https://cloud.githubusercontent.com/assets/6157366/4472452/a305ba6c-4947-11e4-96c8-0a1b36b72ce5.png)

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
