### ISSUE TITLE
404 page when filtering by category and tag  if you turn permalink into other format

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#113]
- go to Dashboard >> Settings >> Permarlink, set into other format ( not default) 

![change-permalink](https://cloud.githubusercontent.com/assets/6157366/4472586/35cc0634-4949-11e4-8d0e-729b71214526.png)

- Go to front-end, click on category/tag of the question 

![click-on-cate-of-question](https://cloud.githubusercontent.com/assets/6157366/4472641/eaff836e-4949-11e4-949b-0f2da3348559.png)

- Result : 404 page

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
