### ISSUE TITLE
How to login or register to ask question?

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#114]
- 1. Go to Backend >> QA >> Settings >> Permission. Here, don't allow anonymous to post question.
- 2. As anonymous, go to front-end, then navigate to " Ask question" page 

_ expected result : There is a message to let anonymous know that they don't have permission to submit question, you must login or register to submit as in single question

![login-or-register](https://cloud.githubusercontent.com/assets/6157366/4472806/a786b222-494b-11e4-88f7-c307ddf92fa5.png)

- Realistic result:

![how-submit-question](https://cloud.githubusercontent.com/assets/6157366/4472847/270c8396-494c-11e4-94cf-13ad421f2482.png)

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
