### ISSUE TITLE
The dropdown question with function edit/delete isn't hidden 

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#115]
![the-box-edit-still-here](https://cloud.githubusercontent.com/assets/6157366/4473021/fd75a54c-494d-11e4-93c3-9ea0c927c442.png)

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
