### ISSUE TITLE
The " insert code" button is broken on firefox and don't show on chrome

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#119]
- On firefox:

![on-firefox](https://cloud.githubusercontent.com/assets/6157366/4501566/e6406bd4-4aae-11e4-9773-7aea02770e5a.png)

- On chrome

![on-chrome](https://cloud.githubusercontent.com/assets/6157366/4501575/50ad2354-4aaf-11e4-9f28-60c4f02ac7d5.png)

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
