### ISSUE TITLE
Can not add private answer

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#121]
- Go to a single question page, then add a private answer

![private-answer](https://cloud.githubusercontent.com/assets/6157366/4539795/e7e76b0e-4e00-11e4-99e8-9ef8a61f491d.png)

- However, after posting the answer, the private answer is switched into Public answer without changing

![can-not-private-answer](https://cloud.githubusercontent.com/assets/6157366/4539824/1ea1f3f8-4e01-11e4-93e3-1e9ea5e64527.png)

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
