### ISSUE TITLE
Can not filter by category

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#122]
- Go to questions list page, click on a category to view all questions which are in that category

![filter-by-cate](https://cloud.githubusercontent.com/assets/6157366/4539853/6be9cea6-4e01-11e4-8141-5ff88c059278.png)

- the result:

![cate-no-correct](https://cloud.githubusercontent.com/assets/6157366/4539892/b3f059a4-4e01-11e4-8a69-6bc10f8d466c.png)

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
