### ISSUE TITLE
Issue: Didn't create db tables for plugin v1.3.2

### ISSUE THREAD

**Issue by Buretta** [designwall/dw-question-answer#125]
just pulled 1.3.2 into fresh WP install, getting error that WP cant find DB tables. I then did a git checkout of v1.3.1 and error resolved, but it's saving to posts table. Assuming 1.3.2 has moved posts to it's own table, but with a fresh install it wasn't created.

**Comment by anna2810** [comment]
Hi Buretta,

Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
