### ISSUE TITLE
Author Name Missing

### ISSUE THREAD

**Issue by eurobank** [designwall/dw-question-answer#126]
Author name missing in question page. Just a | instead.

![screenshot_1](https://cloud.githubusercontent.com/assets/4467158/5025311/f1b32768-6b1f-11e4-922c-d85bcd0015f5.png)

**Comment by eurobank** [comment]
I don't really get it. Why this is not fixed after all those months ?

**Comment by anna2810** [comment]
Hi Eurobank,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
