### ISSUE TITLE
The question author can not view their private question

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#131]
Author can not view their own private question
- as admin can view the private question
http://prntscr.com/59w6l3
- as author, can not view
http://prntscr.com/59w6on

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
