### ISSUE TITLE
The author of the question can not view private answer

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#133]
The author of the question can not view private answer
- as admin, can not see the private answer
http://prntscr.com/59wudq
- as author of the question, can not view it
http://prntscr.com/59wuvd
- As the author of the answer, can not see any sign to know that's private answer
http://prntscr.com/59wvbc

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
