### ISSUE TITLE
Can not filter by category in the 2nd page

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#134]
Can not filter by category in the 2nd page
- If you don't yet filter the question in the 2nd page, all questions own categories. It means that if you filter by category in this page, of course, will show the accurate questions
http://prntscr.com/59wyvc
- However, in practice, no question is shown.
http://prntscr.com/59wzal

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
