### ISSUE TITLE
Can not break line in the comment box

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#138]
both in question and answer comment, can not break line

![comment-line](https://cloud.githubusercontent.com/assets/6157366/5198417/6defbf2c-7583-11e4-8d89-2f809f8c0df0.png)

- but after posting, there is only one line

![only-one-line](https://cloud.githubusercontent.com/assets/6157366/5198454/d5edb21e-7583-11e4-9c44-8d6b0f8ea0f7.png)

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.3 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
