### ISSUE TITLE
Can not extend the textarea in comment box

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#139]
![textarea](https://cloud.githubusercontent.com/assets/6157366/5198642/31ce75e4-7586-11e4-8f16-81f06006af52.png)

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
