### ISSUE TITLE
Permission is incorrect after changing

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#142]
Before changing:Question group, only Admin and contributor can read/post/edit/delete.Answer group, only Admin and contributor can read/post/edit/delete.Comment group, admin and editor can read/post/edit/delete. subscriber,author, contributor can read/post. Anonymous can no nothing.
After changing:Question group, only Admin and contributor can read/post/edit/delete.Answer group, only Admin and contributor can read/post/edit/delete.Comment group, only Admin and contributor can read/post/edit/delete.Then save. and the result is all roles can read/post. only admin, editor,contributor can edit/delete. the result is for all 3 groups.

**Comment by anna2810** [comment]
Hi CarolHayes,

Thank you for noticing us. We do really appreciate your help.

The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.

If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
