### ISSUE TITLE
dwqa permissions page - unable to uncheck "anonymous" settings 

### ISSUE THREAD

**Issue by stevepowell99** [designwall/dw-question-answer#151]
hi, on .../wp-admin/edit.php?post_type=dwqa-question&page=dwqa-settings&tab=permission, if I uncheck all the "read" settings for "anonymous", they return as checked when I save and refresh the page. Specifically it seems like checking the last anonymous/read setting, i.e. in the section for comments, causes the settings for Questions and Answers to become checked again.

**Comment by anna2810** [comment]
Hi Stevepowell99,

Thank you for noticing us. We do really appreciate your help.

The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.

If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
