### ISSUE TITLE
No default settings on the permission 

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#167]
When go to Settings >> Permission, no default selected checks here.
http://prntscr.com/8olrmv

**Comment by anna2810** [comment]
Hi CarolHayes,

Thank you for noticing us. We do really appreciate your help.

The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.

If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
