### ISSUE TITLE
[ DWQA embed question] Please change folder to fit with the DW QA

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#75]
At the moment, when download the DW embed question from WP.org, the plugin is not yet activate

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
