### ISSUE TITLE
don't show avatar if anonymous posts comment

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#84]
![missing-avatar](https://cloud.githubusercontent.com/assets/6157366/3337525/e0796516-f84c-11e3-8b6f-a6b9d226eff2.png)

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
