### ISSUE TITLE
If set up the 404 page is the DWQA Questions/DWQA Ask question page, the page will show with comment box

### ISSUE THREAD

**Issue by CarolHayes** [designwall/dw-question-answer#86]
![404-page](https://cloud.githubusercontent.com/assets/6157366/3337841/467889d2-f852-11e3-9994-67ee284d9a07.png)

**Comment by anna2810** [comment]
Hi CarolHayes,
Thank you for noticing us. We do really appreciate your help.
The issue you mentioned has been solved since the version 1.4.0 of DW Question & Answer. Please update the DW Q&A and continue using it.
If there is any more issue with the plugin, please do not hesitate to get back to us. It encourages us a lot.
